const axios = require('axios');
const fs = require('fs');
const path = require('path');
const { createCanvas, loadImage } = require('canvas');

// Channel info for forwarding
const channelInfo = {
    contextInfo: {
        forwardingScore: 1,
        isForwarded: true,
        forwardedNewsletterMessageInfo: {
            newsletterJid: '120363422591784062@newsletter',
            newsletterName: 'TUNZY-MD',
            serverMessageId: -1
        }
    }
};

// Initialize conversation states
const userStates = new Map();

async function freefireSensitivityCommand(sock, chatId, message, userMessage) {
    const senderId = message.key.participant || message.key.remoteJid;
    
    // Check if user is in a conversation
    if (userStates.has(senderId)) {
        const state = userStates.get(senderId);
        
        if (state.step === 1) {
            // User is entering device name
            state.deviceName = userMessage;
            state.step = 2;
            userStates.set(senderId, state);
            
            await sock.sendMessage(chatId, {
                text: '📱 *Step 2/3*\n\nPlease enter device specifications:\nFormat: *RAM/Space, Android/iPhone*\n\nExample: *8GB/128GB, Android*\n\nOr type *cancel* to cancel'
            }, { quoted: message });
            return;
        }
        
        if (state.step === 2) {
            // User is entering specs
            const specs = userMessage;
            
            // Validate input
            if (specs.toLowerCase() === 'cancel') {
                userStates.delete(senderId);
                await sock.sendMessage(chatId, {
                    text: '❌ Command cancelled.'
                });
                return;
            }
            
            // Parse specs
            const parts = specs.split(',').map(p => p.trim());
            if (parts.length < 2) {
                await sock.sendMessage(chatId, {
                    text: '❌ Invalid format. Please use: *RAM/Space, Android/iPhone*\nExample: *8GB/128GB, Android*'
                }, { quoted: message });
                return;
            }
            
            const [ramSpace, deviceType] = parts;
            const isAndroid = deviceType.toLowerCase().includes('android');
            const isIOS = deviceType.toLowerCase().includes('iphone') || 
                         deviceType.toLowerCase().includes('ios') || 
                         deviceType.toLowerCase().includes('ipad');
            
            if (!isAndroid && !isIOS) {
                await sock.sendMessage(chatId, {
                    text: '❌ Please specify either *Android* or *iPhone/iOS*'
                }, { quoted: message });
                return;
            }
            
            // Generate sensitivity values
            const sensitivityData = await generateSensitivity(state.deviceName, ramSpace, deviceType);
            
            // Create image with overlay
            const imagePath = await createSensitivityImage(sensitivityData);
            
            // Create caption
            let caption = `🎮 *${sensitivityData.deviceName}* 📛\n\n` +
                         `*General* = ${sensitivityData.general}\n` +
                         `*Red dot* = ${sensitivityData.redDot}\n` +
                         `*2x Scope* = ${sensitivityData.scope2x}\n` +
                         `*4x Scope* = ${sensitivityData.scope4x}\n` +
                         `*Sniper Scope* = ${sensitivityData.sniperScope}\n` +
                         `*Free look* = ${sensitivityData.freeLook}\n`;
            
            // Add DPI only for Android
            if (sensitivityData.dpi) {
                caption += `*_DPI_* = ${sensitivityData.dpi}\n\n`;
            } else {
                caption += `\n📱 *iPhone/iOS - No DPI Settings*\n\n`;
            }
            
            caption += `📊 *Device:* ${ramSpace}\n` +
                      `🤖 *Platform:* ${deviceType}\n\n` +
                      `Generated by TUNZY-MD 🫶`;
            
            // Send image with caption
            await sock.sendMessage(chatId, {
                image: fs.readFileSync(imagePath),
                caption: caption,
                ...channelInfo
            }, { quoted: message });
            
            // Clean up
            userStates.delete(senderId);
            
            // Delete temp image after sending
            setTimeout(() => {
                if (fs.existsSync(imagePath)) {
                    fs.unlinkSync(imagePath);
                }
            }, 5000);
            
            return;
        }
    }
    
    // Start new conversation
    if (userMessage === '.freefireesensi') {
        userStates.set(senderId, {
            step: 1,
            deviceName: '',
            conversationStart: Date.now()
        });
        
        await sock.sendMessage(chatId, {
            text: '🎮 *FREE FIRE SENSITIVITY GENERATOR*\n\n' +
                  '*Step 1/3*\n\n' +
                  'Please enter your device name:\n' +
                  'Example: *iPhone 15 Pro Max*, *Samsung S23 Ultra*, *POCO X6 Pro*\n\n' +
                  'Or type *cancel* to cancel'
        }, { quoted: message });
    }
}

async function generateSensitivity(deviceName, ramSpace, deviceType) {
    // Generate Free Fire sensitivity values (range: 1-200)
    const isAndroid = deviceType.toLowerCase().includes('android');
    const isIOS = !isAndroid; // If not Android, assume iOS
    
    // Extract RAM info
    const ramMatch = ramSpace.match(/(\d+)\s*GB/i);
    const ram = ramMatch ? parseInt(ramMatch[1]) : 6;
    
    // Base sensitivity values for Free Fire (1-200 scale)
    // High sensitivity for better control (competitive settings)
    let general, redDot, scope2x, scope4x, sniperScope, freeLook;
    
    // Generate competitive sensitivity based on device type and RAM
    if (isIOS) {
        // iOS devices - generally smoother, can handle higher sensitivity
        if (ram >= 8) {
            // iPhone 15 Pro, iPad Pro - High performance
            general = 95 + Math.floor(Math.random() * 15); // 95-110
            redDot = 85 + Math.floor(Math.random() * 15);  // 85-100
            scope2x = 75 + Math.floor(Math.random() * 10); // 75-85
            scope4x = 60 + Math.floor(Math.random() * 10); // 60-70
            sniperScope = 35 + Math.floor(Math.random() * 10); // 35-45
            freeLook = 100 + Math.floor(Math.random() * 20); // 100-120
        } else if (ram >= 6) {
            // iPhone 14/15 regular - Mid-high performance
            general = 90 + Math.floor(Math.random() * 15); // 90-105
            redDot = 80 + Math.floor(Math.random() * 15);  // 80-95
            scope2x = 70 + Math.floor(Math.random() * 10); // 70-80
            scope4x = 55 + Math.floor(Math.random() * 10); // 55-65
            sniperScope = 30 + Math.floor(Math.random() * 10); // 30-40
            freeLook = 95 + Math.floor(Math.random() * 20); // 95-115
        } else {
            // Older iPhones - Balanced settings
            general = 85 + Math.floor(Math.random() * 15); // 85-100
            redDot = 75 + Math.floor(Math.random() * 15);  // 75-90
            scope2x = 65 + Math.floor(Math.random() * 10); // 65-75
            scope4x = 50 + Math.floor(Math.random() * 10); // 50-60
            sniperScope = 25 + Math.floor(Math.random() * 10); // 25-35
            freeLook = 90 + Math.floor(Math.random() * 20); // 90-110
        }
    } else {
        // Android devices - varies by processor/RAM
        if (ram >= 12) {
            // Flagship Android (S23 Ultra, ROG Phone)
            general = 100 + Math.floor(Math.random() * 20); // 100-120
            redDot = 90 + Math.floor(Math.random() * 15);   // 90-105
            scope2x = 80 + Math.floor(Math.random() * 10);  // 80-90
            scope4x = 65 + Math.floor(Math.random() * 10);  // 65-75
            sniperScope = 40 + Math.floor(Math.random() * 10); // 40-50
            freeLook = 110 + Math.floor(Math.random() * 20); // 110-130
        } else if (ram >= 8) {
            // High-end Android
            general = 95 + Math.floor(Math.random() * 15); // 95-110
            redDot = 85 + Math.floor(Math.random() * 15);  // 85-100
            scope2x = 75 + Math.floor(Math.random() * 10); // 75-85
            scope4x = 60 + Math.floor(Math.random() * 10); // 60-70
            sniperScope = 35 + Math.floor(Math.random() * 10); // 35-45
            freeLook = 105 + Math.floor(Math.random() * 20); // 105-125
        } else if (ram >= 6) {
            // Mid-range Android
            general = 90 + Math.floor(Math.random() * 15); // 90-105
            redDot = 80 + Math.floor(Math.random() * 15);  // 80-95
            scope2x = 70 + Math.floor(Math.random() * 10); // 70-80
            scope4x = 55 + Math.floor(Math.random() * 10); // 55-65
            sniperScope = 30 + Math.floor(Math.random() * 10); // 30-40
            freeLook = 100 + Math.floor(Math.random() * 20); // 100-120
        } else {
            // Low-end Android
            general = 80 + Math.floor(Math.random() * 15); // 80-95
            redDot = 70 + Math.floor(Math.random() * 15);  // 70-85
            scope2x = 60 + Math.floor(Math.random() * 10); // 60-70
            scope4x = 45 + Math.floor(Math.random() * 10); // 45-55
            sniperScope = 25 + Math.floor(Math.random() * 10); // 25-35
            freeLook = 90 + Math.floor(Math.random() * 20); // 90-110
        }
    }
    
    // Ensure values are within Free Fire range (1-200)
    general = Math.min(Math.max(general, 1), 200);
    redDot = Math.min(Math.max(redDot, 1), 200);
    scope2x = Math.min(Math.max(scope2x, 1), 200);
    scope4x = Math.min(Math.max(scope4x, 1), 200);
    sniperScope = Math.min(Math.max(sniperScope, 1), 200);
    freeLook = Math.min(Math.max(freeLook, 1), 200);
    
    // Generate DPI only for Android devices
    let dpi = null;
    if (isAndroid) {
        const androidDPIs = [320, 360, 400, 440, 480, 520, 560];
        dpi = androidDPIs[Math.floor(Math.random() * androidDPIs.length)];
        
        // Adjust DPI based on sensitivity (higher sensitivity = lower DPI for control)
        if (general > 100) dpi -= 40;
        if (general > 120) dpi -= 20;
    }
    
    return {
        deviceName: deviceName.toUpperCase(),
        general: `${general}`,
        redDot: `${redDot}`,
        scope2x: `${scope2x}`,
        scope4x: `${scope4x}`,
        sniperScope: `${sniperScope}`,
        freeLook: `${freeLook}`,
        dpi: dpi ? `${dpi} DPI` : null,
        ramSpace: ramSpace.toUpperCase(),
        deviceType: isIOS ? 'iPhone/iOS' : 'Android'
    };
}

async function createSensitivityImage(data) {
    try {
        // Load the base image from assets
        const baseImagePath = path.join(process.cwd(), 'assets', 'tunzy_sensi.jpg');
        
        if (!fs.existsSync(baseImagePath)) {
            throw new Error('Base image not found at assets/tunzy_sensi.jpg');
        }
        
        // Load the image
        const image = await loadImage(baseImagePath);
        
        // Create canvas with same dimensions as base image
        const canvas = createCanvas(image.width, image.height);
        const ctx = canvas.getContext('2d');
        
        // Draw the base image
        ctx.drawImage(image, 0, 0);
        
        // Set text properties for overlay
        ctx.fillStyle = '#ffffff';
        ctx.font = 'bold 40px Arial';
        ctx.textAlign = 'left';
        
        // Device name (top - adjust position based on your image)
        ctx.fillText(data.deviceName, 100, 120);
        
        // Sensitivity values - YOU NEED TO ADJUST THESE POSITIONS
        // These are example positions - adjust based on your actual image
        
        const sensitivityY = 250; // Start Y position for sensitivity values
        const lineHeight = 55;    // Space between lines
        
        ctx.font = 'bold 36px Arial';
        ctx.fillStyle = '#00ff88'; // Green color for values
        
        // General sensitivity
        ctx.fillText(data.general, 400, sensitivityY);
        
        // Red dot
        ctx.fillText(data.redDot, 400, sensitivityY + lineHeight);
        
        // 2x Scope
        ctx.fillText(data.scope2x, 400, sensitivityY + (lineHeight * 2));
        
        // 4x Scope
        ctx.fillText(data.scope4x, 400, sensitivityY + (lineHeight * 3));
        
        // Sniper Scope
        ctx.fillText(data.sniperScope, 400, sensitivityY + (lineHeight * 4));
        
        // Free look
        ctx.fillText(data.freeLook, 400, sensitivityY + (lineHeight * 5));
        
        // DPI (only for Android)
        if (data.dpi) {
            ctx.fillText(data.dpi, 400, sensitivityY + (lineHeight * 6));
        }
        
        // Device info
        ctx.font = '28px Arial';
        ctx.fillStyle = '#cccccc';
        ctx.fillText(`Device: ${data.ramSpace}`, 100, image.height - 120);
        ctx.fillText(`Platform: ${data.deviceType}`, 100, image.height - 80);
        
        // TUNZY-MD signature
        ctx.fillStyle = '#00ff88';
        ctx.font = 'bold 32px Arial';
        ctx.fillText('TUNZY-MD 🫶', image.width - 250, image.height - 50);
        
        // Save the modified image
        const tempDir = path.join(process.cwd(), 'temp');
        if (!fs.existsSync(tempDir)) {
            fs.mkdirSync(tempDir, { recursive: true });
        }
        
        const outputPath = path.join(tempDir, `tunzy_sensi_${Date.now()}.jpg`);
        const buffer = canvas.toBuffer('image/jpeg', { quality: 0.95 });
        fs.writeFileSync(outputPath, buffer);
        
        return outputPath;
        
    } catch (error) {
        console.error('Error creating sensitivity image:', error);
        
        // Fallback: create a simple text image if base image fails
        return await createFallbackImage(data);
    }
}

async function createFallbackImage(data) {
    // Create a simple fallback image
    const width = 1200;
    const height = 800;
    const canvas = createCanvas(width, height);
    const ctx = canvas.getContext('2d');
    
    // Background
    ctx.fillStyle = '#0a0a0a';
    ctx.fillRect(0, 0, width, height);
    
    // Header with gradient
    const gradient = ctx.createLinearGradient(0, 0, width, 0);
    gradient.addColorStop(0, '#00ff88');
    gradient.addColorStop(1, '#00aaff');
    ctx.fillStyle = gradient;
    ctx.font = 'bold 60px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('TUNZY - MD - SENSITIVITY 🫶', width / 2, 100);
    
    // Device name
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 48px Arial';
    ctx.fillText(data.deviceName, width / 2, 180);
    
    // Sensitivity values in a grid
    ctx.font = 'bold 40px Arial';
    ctx.textAlign = 'left';
    
    const leftColumn = 150;
    const rightColumn = 650;
    const startY = 280;
    const lineHeight = 70;
    
    // Left column
    ctx.fillStyle = '#00ff88';
    ctx.fillText(`General: ${data.general}`, leftColumn, startY);
    ctx.fillText(`Red dot: ${data.redDot}`, leftColumn, startY + lineHeight);
    ctx.fillText(`2x Scope: ${data.scope2x}`, leftColumn, startY + (lineHeight * 2));
    
    // Right column
    ctx.fillText(`4x Scope: ${data.scope4x}`, rightColumn, startY);
    ctx.fillText(`Sniper: ${data.sniperScope}`, rightColumn, startY + lineHeight);
    ctx.fillText(`Free look: ${data.freeLook}`, rightColumn, startY + (lineHeight * 2));
    
    // DPI (only for Android)
    if (data.dpi) {
        ctx.fillStyle = '#ffaa00';
        ctx.font = 'bold 44px Arial';
        ctx.textAlign = 'center';
        ctx.fillText(`DPI: ${data.dpi}`, width / 2, startY + (lineHeight * 3.5));
    }
    
    // Device info
    ctx.fillStyle = '#888888';
    ctx.font = '32px Arial';
    ctx.textAlign = 'left';
    ctx.fillText(`📱 Device: ${data.ramSpace}`, 150, height - 150);
    ctx.fillText(`🤖 Platform: ${data.deviceType}`, 150, height - 100);
    
    // Footer
    ctx.fillStyle = '#00ff88';
    ctx.font = 'bold 36px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('Generated by TUNZY-MD | Free Fire Pro Settings', width / 2, height - 30);
    
    // Save image
    const tempDir = path.join(process.cwd(), 'temp');
    if (!fs.existsSync(tempDir)) {
        fs.mkdirSync(tempDir, { recursive: true });
    }
    
    const outputPath = path.join(tempDir, `tunzy_sensi_fallback_${Date.now()}.jpg`);
    const buffer = canvas.toBuffer('image/jpeg', { quality: 0.95 });
    fs.writeFileSync(outputPath, buffer);
    
    return outputPath;
}

module.exports = freefireSensitivityCommand;
